### PR TITLE
chore(dep): migrate to `pnpm` #24

### PR DESCRIPTION
**Pull request by priyankarpal**
## Fixed issue
- #24 

## Preview

https://github.com/AlphaDecodeX/NoMise_Store/assets/88102392/078bddb0-5bb7-49eb-b5c2-08603af34e1c

## File changed
- README.md file
- upgraded dependencies `package.json`
- added new files `pnpm-lock.yaml` &   `pnpm-workspace.yaml`
- deleted `package-lock.json`

### CODE REVIEW

**Comment by AlphaDecodeX** [comment]
@priyankarpal Can you add the instructions in Readme.md too for this change?

**Comment by priyankarpal** [comment]
> @priyankarpal Can you add the instructions in Readme.md too for this change?

like ig I already added. `pnpm i` & `pnpm dev`.

also, we need to create contributing guide

**Comment by AlphaDecodeX** [comment]
@priyankarpal Yeah, I don't know about general practices that people follow in Open Source Projects. It would be appreciable if you can add Contributing guide or other things in general..

**Review by AlphaDecodeX — APPROVED** [review]

**Comment by priyankarpal** [comment]
> @priyankarpal Yeah, I don't know about general practices that people follow in Open Source Projects. It would be appreciable if you can add Contributing guide or other things in general..

yeah I will add

**Pull request merged**
